# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'MessageService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MessageService.proto\"J\n\x15PrivateMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"W\n\x0fMessageResponse\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\".\n\x1aMessageSubscriptionRequest\x12\x10\n\x08username\x18\x01 \x01(\t2\x8f\x01\n\x0eMessageService\x12\x37\n\x0bSendMessage\x12\x16.PrivateMessageRequest\x1a\x10.MessageResponse\x12\x44\n\x11SubscribeMessages\x12\x1b.MessageSubscriptionRequest\x1a\x10.MessageResponse0\x01\x42 \n\x07messageB\x13MessageServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\007messageB\023MessageServiceProtoP\001'
  _globals['_PRIVATEMESSAGEREQUEST']._serialized_start=24
  _globals['_PRIVATEMESSAGEREQUEST']._serialized_end=98
  _globals['_MESSAGERESPONSE']._serialized_start=100
  _globals['_MESSAGERESPONSE']._serialized_end=187
  _globals['_MESSAGESUBSCRIPTIONREQUEST']._serialized_start=189
  _globals['_MESSAGESUBSCRIPTIONREQUEST']._serialized_end=235
  _globals['_MESSAGESERVICE']._serialized_start=238
  _globals['_MESSAGESERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
