# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PostService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'PostService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PostService.proto\"6\n\x11\x43reatePostRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"D\n\x0cPostResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"$\n\x10SubscribeRequest\x12\x10\n\x08username\x18\x01 \x01(\t2t\n\x0bPostService\x12/\n\nCreatePost\x12\x12.CreatePostRequest\x1a\r.PostResponse\x12\x34\n\x0eSubscribePosts\x12\x11.SubscribeRequest\x1a\r.PostResponse0\x01\x42\x1a\n\x04postB\x10PostServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PostService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\004postB\020PostServiceProtoP\001'
  _globals['_CREATEPOSTREQUEST']._serialized_start=21
  _globals['_CREATEPOSTREQUEST']._serialized_end=75
  _globals['_POSTRESPONSE']._serialized_start=77
  _globals['_POSTRESPONSE']._serialized_end=145
  _globals['_SUBSCRIBEREQUEST']._serialized_start=147
  _globals['_SUBSCRIBEREQUEST']._serialized_end=183
  _globals['_POSTSERVICE']._serialized_start=185
  _globals['_POSTSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
