server:
  port: 8080

grpc:
  server:
    port: 9090

election:
    others: "1,2"


spring:
  application:
    name: social-network-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
