server:
  port: 8082

grpc:
  server:
    port: 9092

election:
  others: "0,1"

spring:
  application:
    name: social-network-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
