# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mensagem_pb2 as mensagem__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mensagem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MensagemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarMensagem = channel.unary_unary(
                '/mensagens.MensagemService/EnviarMensagem',
                request_serializer=mensagem__pb2.Mensagem.SerializeToString,
                response_deserializer=mensagem__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.ChatMensagens = channel.stream_stream(
                '/mensagens.MensagemService/ChatMensagens',
                request_serializer=mensagem__pb2.Mensagem.SerializeToString,
                response_deserializer=mensagem__pb2.Mensagem.FromString,
                _registered_method=True)
        self.ObterTempoVivo = channel.unary_unary(
                '/mensagens.MensagemService/ObterTempoVivo',
                request_serializer=mensagem__pb2.Vazio.SerializeToString,
                response_deserializer=mensagem__pb2.Tempo.FromString,
                _registered_method=True)
        self.AjustarTempo = channel.unary_unary(
                '/mensagens.MensagemService/AjustarTempo',
                request_serializer=mensagem__pb2.DeltaTempo.SerializeToString,
                response_deserializer=mensagem__pb2.Vazio.FromString,
                _registered_method=True)


class MensagemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnviarMensagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatMensagens(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterTempoVivo(self, request, context):
        """Adicionados para sincronização de relógio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AjustarTempo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MensagemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarMensagem,
                    request_deserializer=mensagem__pb2.Mensagem.FromString,
                    response_serializer=mensagem__pb2.Confirmacao.SerializeToString,
            ),
            'ChatMensagens': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatMensagens,
                    request_deserializer=mensagem__pb2.Mensagem.FromString,
                    response_serializer=mensagem__pb2.Mensagem.SerializeToString,
            ),
            'ObterTempoVivo': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterTempoVivo,
                    request_deserializer=mensagem__pb2.Vazio.FromString,
                    response_serializer=mensagem__pb2.Tempo.SerializeToString,
            ),
            'AjustarTempo': grpc.unary_unary_rpc_method_handler(
                    servicer.AjustarTempo,
                    request_deserializer=mensagem__pb2.DeltaTempo.FromString,
                    response_serializer=mensagem__pb2.Vazio.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mensagens.MensagemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mensagens.MensagemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MensagemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnviarMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mensagens.MensagemService/EnviarMensagem',
            mensagem__pb2.Mensagem.SerializeToString,
            mensagem__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatMensagens(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mensagens.MensagemService/ChatMensagens',
            mensagem__pb2.Mensagem.SerializeToString,
            mensagem__pb2.Mensagem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterTempoVivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mensagens.MensagemService/ObterTempoVivo',
            mensagem__pb2.Vazio.SerializeToString,
            mensagem__pb2.Tempo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AjustarTempo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mensagens.MensagemService/AjustarTempo',
            mensagem__pb2.DeltaTempo.SerializeToString,
            mensagem__pb2.Vazio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
