# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mensagem.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mensagem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emensagem.proto\x12\tmensagens\"I\n\x08Mensagem\x12\n\n\x02\x64\x65\x18\x01 \x01(\t\x12\x0c\n\x04para\x18\x02 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\"\x1f\n\x0b\x43onfirmacao\x12\x10\n\x08recebido\x18\x01 \x01(\x08\"\x07\n\x05Vazio\"\x16\n\x05Tempo\x12\r\n\x05tempo\x18\x01 \x01(\x01\"\x1b\n\nDeltaTempo\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\x01\x32\xfe\x01\n\x0fMensagemService\x12=\n\x0e\x45nviarMensagem\x12\x13.mensagens.Mensagem\x1a\x16.mensagens.Confirmacao\x12=\n\rChatMensagens\x12\x13.mensagens.Mensagem\x1a\x13.mensagens.Mensagem(\x01\x30\x01\x12\x34\n\x0eObterTempoVivo\x12\x10.mensagens.Vazio\x1a\x10.mensagens.Tempo\x12\x37\n\x0c\x41justarTempo\x12\x15.mensagens.DeltaTempo\x1a\x10.mensagens.Vaziob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensagem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAGEM']._serialized_start=29
  _globals['_MENSAGEM']._serialized_end=102
  _globals['_CONFIRMACAO']._serialized_start=104
  _globals['_CONFIRMACAO']._serialized_end=135
  _globals['_VAZIO']._serialized_start=137
  _globals['_VAZIO']._serialized_end=144
  _globals['_TEMPO']._serialized_start=146
  _globals['_TEMPO']._serialized_end=168
  _globals['_DELTATEMPO']._serialized_start=170
  _globals['_DELTATEMPO']._serialized_end=197
  _globals['_MENSAGEMSERVICE']._serialized_start=200
  _globals['_MENSAGEMSERVICE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
